before_script:
  - "pip3 install -r .ci/requirements.txt"
  - "REQUIREMENTS=$(mktemp) && python3 setup.py requirements > ${REQUIREMENTS} && pip3 install -r ${REQUIREMENTS} && rm ${REQUIREMENTS}"
  - "pip3 install -r .ci/requirements_modules.txt"

build:2.7:
  image: "python:2.7"
  stage: "build"
  script:
    - "./tools/local_install.sh -2 ~/bin"

pyflakes:2.7:
  image: "python:2.7"
  stage: "test"
  script:
    - "./tools/pyflakes.sh -2"

lint:2.7:
  image: "python:2.7"
  stage: "test"
  allow_failure: true
  script:
    - "./tools/weboob_lint.sh -2"

unittests:2.7:
  image: "python:2.7"
  stage: "test"
  script:
    - "./tools/run_tests.sh -2 --no-modules"

unittests-modules:2.7:
  image: "python:2.7"
  stage: "test"
  allow_failure: true
  script:
    - "./tools/run_tests.sh -2 --no-core"

doc:2.7:
  image: "python:2.7"
  stage: "deploy"
  script:
    - "cd ./docs && make html"

build:3:
  image: "python:3"
  stage: "build"
  script:
    - "./tools/local_install.sh ~/bin"

pyflakes:3:
  image: "python:3"
  stage: "test"
  script:
      - "./tools/pyflakes.sh"

lint:3:
  image: "python:3"
  stage: "test"
  allow_failure: true
  script:
    - "./tools/weboob_lint.sh"

unittests:3:
  image: "python:3"
  stage: "test"
  script:
    - "./tools/run_tests.sh --no-modules"

unittests-modules:3:
  image: "python:3"
  stage: "test"
  allow_failure: true
  script:
    - "./tools/run_tests.sh --no-core"

doc:3:
  image: "python:3"
  stage: "deploy"
  script:
    - "cd ./docs && make html"
