before_script:
  - "pip install -r .ci/requirements.txt"
  - "REQUIREMENTS=$(mktemp) && python setup.py requirements > ${REQUIREMENTS} && pip install -r ${REQUIREMENTS} && rm ${REQUIREMENTS}"
  - "pip install -r .ci/requirements_modules.txt"

stages:
  - "build27"
  - "test27"
  - "deploy27"
  - "build3"
  - "test3"
  - "deploy3"

build:2.7:
  image: "python:2.7"
  stage: "build27"
  script:
    - "./tools/local_install.sh ~/bin"

lint:2.7:
  image: "python:2.7"
  stage: "test27"
  script:
    - "./tools/pyflakes.sh"
    - "./tools/weboob_lint.sh"

unittests:2.7:
  image: "python:2.7"
  stage: "test27"
  script:
    - "./tools/run_tests.sh"

doc:2.7:
  image: "python:2.7"
  stage: "deploy27"
  script:
    - "cd ./docs && make html"

build:3:
  image: "python:3"
  stage: "build3"
  script:
    - "./tools/local_install.sh ~/bin"

lint:3:
  image: "python:3"
  stage: "test3"
  script:
    - "./tools/pyflakes.sh"
    - "./tools/weboob_lint.sh"

unittests:3:
  image: "python:3"
  stage: "test3"
  script:
    - "./tools/run_tests.sh -3"

doc:3:
  image: "python:3"
  stage: "deploy3"
  script:
    - "cd ./docs && make html"
